type BonusDeus = {
  pericia?: string; // "atletismo", "arcanismo"
  ataque?: boolean; // true → vale para ataques
  valor: number;
  nivelMin: number;
  titulo: string;
  especial?: boolean; // bifurcação / poder especial
  condicional?: string; // futuro: "mar", "molhado", etc
  substitui?: string;
};

type BonusPorDeus = Record<string, BonusDeus[]>;

export const BONUS_DEUSES: BonusPorDeus = {
  poseidon: [
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 1,
      titulo: "Eu na Praia",
      condicional: "estar no mar",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 1,
      titulo: "Dominação Aquática Inicial",
    },
    {
      pericia: "atletismo",
      valor: 2,
      nivelMin: 1,
      titulo: "Peixinho Fora D’Água",
    },
    {
      pericia: "condução",
      valor: 2,
      nivelMin: 1,
      titulo: "Peixinho Fora D’Água",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 3,
      titulo: "Dominação Aquática Treinada",
      substitui: "Dominação Aquática Inicial",
    },
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 3,
      titulo: "Eu no litoral",
      condicional: "precisa estar no litoral e soma +1 se estiver no mar",
      substitui: "Eu na praia",
    },
    {
      pericia: "arcanismo",
      valor: 4,
      nivelMin: 5,
      titulo: "Dominação Aquática Avançada",
      substitui: "Dominação Aquática Treinada",
    },
  ],
  zeus: [
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 1,
      titulo: "Dominação Tempestuosa Inicial",
    },
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 1,
      titulo: "Portador das Tempestades",
      condicional: "lugares altos ou clima tempestuoso",
    },
    {
      pericia: "persuasão",
      valor: 2,
      nivelMin: 1,
      titulo: "Vontade do Rei",
    },
    {
      pericia: "adestramento",
      valor: 2,
      nivelMin: 1,
      titulo: "Vontade do Rei",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 3,
      titulo: "Dominação Tempestuosa Treinada",
      substitui: "Dominação Tempestuosa Inicial",
    },
    {
      pericia: "persuasão",
      valor: 4,
      nivelMin: 3,
      titulo: "Manipulação da Névoa",
      condicional: "contra humanos comuns",
    },
    {
      pericia: "enganação",
      valor: 4,
      nivelMin: 3,
      titulo: "Manipulação da Névoa",
      condicional: "contra humanos comuns",
    },
    {
      ataque: true,
      valor: 1,
      nivelMin: 4,
      titulo: "Soberania Olimpiana",
      condicional:
        "1 por herdeiro olimpiano próximo - exceto Hades e Poseidon (máx 4)",
    },
    {
      pericia: "arcanismo",
      valor: 4,
      nivelMin: 5,
      titulo: "Dominação Tempestuosa Avançada",
      substitui: "Dominação Tempestuosa Treinada",
    },
  ],
  hades: [
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 1,
      titulo: "Dominação Obscura Inicial",
    },
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 2,
      titulo: "Filho do Dono",
      condicional: "submundo, cemitérios ou áreas de morte",
    },
    {
      pericia: "intimidacao",
      valor: 2,
      nivelMin: 2,
      titulo: "Você Tem Uma Energia Estranha",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 3,
      titulo: "Dominação Obscura Treinada",
      substitui: "Dominação Obscura Inicial",
    },
    {
      pericia: "arcanismo",
      valor: 4,
      nivelMin: 5,
      titulo: "Dominação Obscura Avançada",
      substitui: "Dominação Obscura Treinada",
    },
  ],
  afrodite: [
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 1,
      titulo: "Aliança Jovial",
      condicional: "se estiver ao lado de alguém que tenha afeição romântica",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 1,
      titulo: "Aliança Jovial",
      condicional: "Caso possua Sinergia com alguém em Batalha",
    },

    {
      pericia: "persuasao",
      valor: 2,
      nivelMin: 2,
      titulo: "Tipo de Todo Mundo",
    },
    {
      pericia: "adestramento",
      valor: 2,
      nivelMin: 6,
      titulo: "Linguagem Universal",
    },
  ],
  apolo: [
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 1,
      titulo: "Dominação Luminosa Inicial",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 1,
      titulo: "Artista Solar",
      condicional: "se estiver de dia (das 6h às 18h)",
    },
    {
      pericia: "performance",
      valor: 2,
      nivelMin: 1,
      titulo: "Artista Solar",
    },
    {
      pericia: "arqueirismo",
      valor: 2,
      nivelMin: 2,
      titulo: "Mestre das Flechas",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 2,
      titulo: "Sol da Meia-noite",
      condicional: "precisa ter a bifurcação",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 3,
      titulo: "Dominação Luminosa Treinada",
      substitui: "Dominação Luminosa Inicial",
    },
    {
      pericia: "percepção",
      valor: 3,
      nivelMin: 5,
      titulo: "Sonhos Proféticos",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 5,
      titulo: "Dominação Luminosa Avançada",
      substitui: "Dominação Luminosa Treinada",
    },
  ],
  ares: [
    {
      pericia: "atletismo",
      valor: 2,
      nivelMin: 1,
      titulo: "Proficiência Física",
    },
    {
      pericia: "armas brancas",
      valor: 2,
      nivelMin: 2,
      titulo: "Mestre das armas",
    },
    {
      pericia: "intimidação",
      valor: 2,
      nivelMin: 2,
      titulo: "Carranca intimidante",
    },
    {
      pericia: "religião",
      valor: 2,
      nivelMin: 4,
      titulo: "Guerra Lovers",
      condicional: "somente ao longo das três rodadas posteriores a primeira.",
    },
    {
      ataque: true,
      valor: 2,
      nivelMin: 4,
      titulo: "Guerra Lovers",
      condicional:
        "somente ao longo das três rodadas posteriores a primeira e no máximo em 2 poderes por vez.",
    },
  ],
  atena: [
    {
      pericia: "história",
      valor: 2,
      nivelMin: 2,
      titulo: "Conhecedora de tudo",
    },
    {
      pericia: "investigação",
      valor: 2,
      nivelMin: 2,
      titulo: "Olho de detetive",
    },
    {
      pericia: "percepção",
      valor: 2,
      nivelMin: 3,
      titulo: "Potencial defensivo",
    },
  ],
  demeter: [
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 1,
      titulo: "Dominação Vegetal Inicial",
    },
    {
      pericia: "botânica",
      valor: 2,
      nivelMin: 1,
      titulo: "Vegano de berço",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 3,
      titulo: "Dominação Vegetal Treinada",
      substitui: "Dominação Vegetal Inicial",
    },
    {
      pericia: "sobrevivência",
      valor: 2,
      nivelMin: 3,
      titulo: "Mapeamento Natural",
    },
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 4,
      titulo: "Mapeamento Natural",
      condicional: "se estiver no verão",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 5,
      titulo: "Dominação Vegetal Avançada",
      substitui: "Dominação Vegetal Treinada",
    },
    {
      pericia: "percepção",
      valor: 2,
      nivelMin: 5,
      titulo: "Vínculo com a natureza",
      condicional: "se houver plantas por perto",
    },
    {
      pericia: "sobrevivência",
      valor: 2,
      nivelMin: 5,
      titulo: "Vínculo com a natureza",
      condicional: "se houver plantas por perto",
    },
    {
      pericia: "investigação",
      valor: 2,
      nivelMin: 5,
      titulo: "Vínculo com a natureza",
      condicional: "se houver plantas por perto",
    },
  ],
  dionísio: [
    {
      pericia: "performance",
      valor: 2,
      nivelMin: 1,
      titulo: "Ator principiante",
    },
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 1,
      titulo: "Dominação vegetal inicial",
    },
    {
      pericia: "história",
      valor: 2,
      nivelMin: 2,
      titulo: "Diretor e roteirista",
    },
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 2,
      titulo: "Euforia natural",
      condicional:
        "se estiver acometido por euforia (embriaguez), vale por 2 rodadas",
    },
    {
      pericia: "botânica",
      valor: 2,
      nivelMin: 3,
      titulo: "Agente da fertilidade",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 3,
      titulo: "Dominação vegetal treinada",
      substitui: "Dominação vegetal inicial",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 5,
      titulo: "Dominação vegetal avançada",
      substitui: "Dominação vegetal treinada",
    },
    {
      pericia: "religião",
      valor: 2,
      nivelMin: 6,
      titulo: "Embriaguez religiosa",
    },
  ],
  hefesto: [
    {
      pericia: "ofícios",
      valor: 1,
      nivelMin: 1,
      titulo: "Pátria educadora",
    },
    {
      pericia: "mecânica",
      valor: 1,
      nivelMin: 1,
      titulo: "Pátria educadora",
    },
    {
      pericia: "mecânica",
      valor: 2,
      nivelMin: 2,
      titulo: "Arauto das máquinas",
      condicional: "precisa ter a bifurcação",
    },
    {
      pericia: "armas brancas",
      valor: 2,
      nivelMin: 2,
      titulo: "Mestre das armas",
      condicional: "precisa ter a bifurcação",
    },
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 2,
      titulo: "Dominação flamejante",
      condicional: "precisa ter a bifurcação",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 4,
      titulo: "Dominação flamejante - nível 4",
      condicional: "precisa ter a bifurcação",
      substitui: "Dominação flamejante",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 6,
      titulo: "Dominação flamejante - nível 6",
      condicional: "precisa ter a bifurcação",
      substitui: "Dominação flamejante - nível 4",
    },
    {
      pericia: "computação",
      valor: 2,
      nivelMin: 4,
      titulo: "Intelectualidade tecnológica",
      condicional: "precisa ter a bifurcação",
    },
    {
      pericia: "linguagens",
      valor: 3,
      nivelMin: 5,
      titulo: "Expert em sistemas",
    },
  ],
  hermes: [
    {
      pericia: "enganação",
      valor: 2,
      nivelMin: 1,
      titulo: "Bom de lábia",
    },
    {
      pericia: "prestidigitação",
      valor: 2,
      nivelMin: 1,
      titulo: "Mãos leves",
    },
    {
      pericia: "furtividade",
      valor: 2,
      nivelMin: 2,
      titulo: "Andar de ladrão",
    },
    {
      pericia: "atletismo",
      valor: 2,
      nivelMin: 2,
      titulo: "Histórico de atleta",
    },
    {
      pericia: "linguagens",
      valor: 3,
      nivelMin: 5,
      titulo: "Ticket humano",
    },
    {
      pericia: "todas",
      valor: 3,
      nivelMin: 5,
      titulo: "Ticket humano",
      condicional: "em missões, em rodadas de deslocamento",
    },
  ],
  anfitrite: [
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 1,
      titulo: "Espírito dos Mares",
      condicional: "precisar estar em ambientes aquáticos ou praias",
    },
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 1,
      titulo: "Dominação Aquática Inicial",
    },
    {
      pericia: "performance",
      valor: 2,
      nivelMin: 1,
      titulo: "Timbre perfeito",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 3,
      titulo: "Dominação Aquática Treinada",
      substitui: "Dominação Aquática Inicial",
    },
    {
      pericia: "medicina",
      valor: 2,
      nivelMin: 3,
      titulo: "Pureza da água",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 5,
      titulo: "Dominação Aquática Avançada",
      substitui: "Dominação Aquática Treinada",
    },
  ],
  perséfone: [
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 1,
      titulo: "Dominação Vegetal Inicial",
    },
    {
      pericia: "botânica",
      valor: 2,
      nivelMin: 1,
      titulo: "Rainha da Primavera",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 1,
      titulo: "Rainha da Primavera",
      condicional: "precisa estar na primavera",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 2,
      titulo: "Dualidade da rainha",
      condicional: "precisa estar em ambientes recheados de morte",
    },
    {
      pericia: "persuasão",
      valor: 2,
      nivelMin: 2,
      titulo: "Dualidade da rainha",
    },
    {
      pericia: "persuasão",
      valor: 2,
      nivelMin: 2,
      titulo: "Aromaterapia Natural",
      condicional: "precisa ter a bifurcação",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 3,
      titulo: "Dominação Vegetal Treinada",
      substitui: "Dominação Vegetal Inicial",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 4,
      titulo: "Dominação obscura",
      condicional: "precisa ter a bifurcação e estar nas sombras",
    },
    {
      pericia: "arcanismo",
      valor: 4,
      nivelMin: 6,
      titulo: "Dominação obscura - nível 6",
      condicional: "precisa ter a bifurcação e estar nas sombras",
      substitui: "Dominação obscura",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 5,
      titulo: "Dominação Vegetal Avançada",
      substitui: "Dominação Vegetal Treinada",
    },
    {
      pericia: "botânica",
      valor: 2,
      nivelMin: 6,
      titulo: "Maratona das Plantas",
    },
  ],
  aracne: [
    {
      pericia: "ofícios",
      valor: 2,
      nivelMin: 2,
      titulo: "Mãos habilidosas",
    },
    {
      pericia: "investigação",
      valor: 2,
      nivelMin: 4,
      titulo: "Sentido aranha",
    },
    {
      pericia: "percepção",
      valor: 2,
      nivelMin: 4,
      titulo: "Sentido aranha",
    },
    {
      pericia: "ofícios",
      valor: 2,
      nivelMin: 4,
      titulo: "Costura elaborada",
      condicional: "precisa ter a bifurcação",
    },
    {
      pericia: "furtividade",
      valor: 3,
      nivelMin: 5,
      titulo: "Furtiva e Misteriosa",
    },
    {
      pericia: "adestramento",
      valor: 2,
      nivelMin: 6,
      titulo: "Caçadora nata",
    },
    {
      pericia: "intimidação",
      valor: 2,
      nivelMin: 6,
      titulo: "Caçadora nata",
    },
  ],
  asclépio: [
    {
      pericia: "medicina",
      valor: 2,
      nivelMin: 1,
      titulo: "Dr. Asclépio",
    },
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 2,
      titulo: "Dominação Sanguínea Inicial",
    },
    {
      pericia: "botânica",
      valor: 2,
      nivelMin: 3,
      titulo: "Conhecimento botânico",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 4,
      titulo: "Dominação Sanguínea Treinada",
      substitui: "Dominação Sanguínea Inicial",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 6,
      titulo: "Dominação Sanguínea Avançada",
      substitui: "Dominação Sanguínea Treinada",
    },
    {
      pericia: "religião",
      valor: 2,
      nivelMin: 6,
      titulo: "Redenção",
      condicional: "precisa ter a bifurcação",
    },
  ],
  astreia: [
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 1,
      titulo: "Dominação Estelar Inicial",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 1,
      titulo: "Hora da Estrela",
      condicional: "se estiver de noite (entre 18h e 6h)",
    },
    {
      pericia: "intuição",
      valor: 1,
      nivelMin: 1,
      titulo: "Matrona da Justiça",
    },
    {
      pericia: "percepção",
      valor: 1,
      nivelMin: 1,
      titulo: "Matrona da Justiça",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 3,
      titulo: "Dominação Estelar Treinada",
      substitui: "Dominação Estelar Inicial",
    },
    {
      pericia: "furtividade",
      valor: 2,
      nivelMin: 3,
      titulo: "Gravitação Estelar",
    },
    {
      ataque: true,
      valor: 2,
      nivelMin: 3,
      titulo: "Poder da Constelação",
      condicional: "precisa estar ao lado de algum irmão",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 5,
      titulo: "Dominação Estelar Avançada",
      substitui: "Dominação Estelar Treinada",
    },
  ],
  bia: [
    {
      pericia: "religião",
      valor: 2,
      nivelMin: 1,
      titulo: "Às margens do Rio Estige",
    },
    {
      pericia: "atletismo",
      valor: 2,
      nivelMin: 1,
      titulo: "Força aplicada",
    },
    {
      pericia: "combate desarmado",
      valor: 2,
      nivelMin: 2,
      titulo: "Duelista marcial",
    },
    {
      ataque: true,
      valor: 2,
      nivelMin: 3,
      titulo: "Luta justa",
      condicional:
        "Afetado por status de efeito ou atacado por pelo menos dois alvos, válido por duas rodadas.",
    },
  ],
  circe: [
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 1,
      titulo: "Dominação Arcana Inicial",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 2,
      titulo: "Congregação bruxa",
      condicional:
        "+1 a cada semideus herdeiro de deusa bruxa que estiver perto, máximo +3",
    },
    {
      pericia: "botânica",
      valor: 2,
      nivelMin: 2,
      titulo: "Saberes da naturezas",
    },
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 2,
      titulo: "Filha do Sol",
      condicional: "precisa ser um teste, precisa estar de dia (das 6h às 18h)",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 3,
      titulo: "Dominação Arcana Treinada",
      substitui: "Dominação Arcana Inicial",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 5,
      titulo: "Dominação Arcana Avançada",
      substitui: "Dominação Arcana Treinada",
    },
  ],
  "fobos e deimos": [
    {
      pericia: "intimidação",
      valor: 2,
      nivelMin: 2,
      titulo: "Mestres do Terror",
    },
    {
      pericia: "intimidação",
      valor: 1,
      nivelMin: 2,
      titulo: "Sede por Temor",
      condicional:
        "precisa estar próximo de alguém afetado por pavor, ou alvos persuadidos por intimidação ou alguém com 1/3 de HP",
    },
    {
      ataque: true,
      valor: 1,
      nivelMin: 2,
      titulo: "Sede por Temor",
      condicional:
        "precisa estar próximo de alguém afetado por pavor, ou alvos persuadidos por intimidação ou alguém com 1/3 de HP",
    },
    {
      pericia: "armas brancas",
      valor: 2,
      nivelMin: 2,
      titulo: "Guerreiro Ambidestro",
      condicional: "precisa estar com duas armas e precisa ter a bifurcação",
    },
    {
      pericia: "percepção",
      valor: 2,
      nivelMin: 3,
      titulo: "Detecção de Temores",
    },
    {
      pericia: "intuição",
      valor: 2,
      nivelMin: 3,
      titulo: "Detecção de Temores",
    },
    {
      ataque: true,
      valor: 1,
      nivelMin: 4,
      titulo: "Inspiração degenerada",
      condicional: "+1 para cada inimigo abatido presente",
    },
    {
      ataque: true,
      valor: 1,
      nivelMin: 4,
      titulo: "Sinergia de Guerra",
      condicional:
        "+1 para cada inimigo com status de efeito negativo de dano contínuo",
    },
    {
      pericia: "intimidação",
      valor: 1,
      nivelMin: 4,
      titulo: "Sinergia de Guerra",
      condicional:
        "+1 para cada inimigo com status de efeito negativo de dano contínuo",
    },
    {
      ataque: true,
      valor: 3,
      nivelMin: 5,
      titulo: "Pavorosos de berço",
      condicional:
        "precisa estar afetado por pavor ou paranoia, bônus dura três rodadas",
    },
    {
      ataque: true,
      valor: 1,
      nivelMin: 5,
      titulo: "Prefiro a morte",
      condicional:
        "+1 a cada monstro com pavor ou paranoia com menos de 5HP (nesse caso, eles também morrem automaticamente)",
    },
    {
      ataque: true,
      valor: 2,
      nivelMin: 6,
      titulo: "Duelistas sanguinários",
      condicional:
        "+2 a cada 12 de dano sofrido (incluindo dano negado por armaduras)",
    },
    {
      ataque: true,
      valor: 3,
      nivelMin: 6,
      titulo: "Ombro a ombro",
      condicional:
        "precisa estar ao lado de um amigo, irmão ou alguém com 15 pontos em intimidação (ambos ganham +3 atk e +2 dmg ao atacar mesmo alvo)",
    },
  ],
  despina: [
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 1,
      titulo: "Dominação Glacial Inicial",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 1,
      titulo: "Friozinho gostoso",
      condicional: "precisa estar no inverno ou em lugares glaciais",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 2,
      titulo: "Picolé humano",
      condicional:
        "precisa ter a bifurcação e estar no inverno ou em lugares glaciais",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 3,
      titulo: "Dominação Glacial Treinada",
      substitui: "Dominação Glacial Inicial",
    },
    {
      pericia: "todas",
      valor: 3,
      nivelMin: 3,
      titulo: "Monisi",
      condicional: "precisa estar sozinho",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 5,
      titulo: "Dominação Glacial Avançada",
      substitui: "Dominação Glacial Treinada",
    },
  ],
  ênio: [
    {
      ataque: true,
      valor: 1,
      nivelMin: 2,
      titulo: "Séquito de Ares",
      condicional:
        "precisa estar perto de um filho de Ares ou um semideus agressivo e intimidante (com pelo menos +2 de intimidação)",
    },
    {
      pericia: "intimidação",
      valor: 2,
      nivelMin: 2,
      titulo: "Horror da Batalha",
      condicional: "precisa ter a bifurcação",
    },
    {
      ataque: true,
      valor: 1,
      nivelMin: 5,
      titulo: "Até a morte",
      condicional: "ao perder 15hp",
    },
    {
      ataque: true,
      valor: 2,
      nivelMin: 5,
      titulo: "Até a morte",
      condicional: "ao perder metade do hp (soma com +1 de ter perdido 15)",
    },
    {
      ataque: true,
      valor: 2,
      nivelMin: 5,
      titulo: "Até a morte",
      condicional:
        "quando só faltar 10HP ou menos (soma com +3 de ter perdido metade)",
    },
  ],
  éolo: [
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 1,
      titulo: "Dominação Eólica Inicial",
    },
    {
      pericia: "percepção",
      valor: 2,
      nivelMin: 1,
      titulo: "Ouvido de mãe",
    },
    {
      pericia: "arremessáveis",
      valor: 2,
      nivelMin: 2,
      titulo: "Eita como arremessa",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 3,
      titulo: "Dominação Eólica Treinada",
      substitui: "Dominação Eólica Inicial",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 5,
      titulo: "Dominação Eólica Avançada",
      substitui: "Dominação Eólica Treinada",
    },
  ],
  eos: [
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 1,
      titulo: "Dominação Crepuscular Inicial",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 1,
      titulo: "Seja dia ou seja noite",
      condicional: "precisa estar em lugar aberto",
    },
    {
      pericia: "percepção",
      valor: 1,
      nivelMin: 2,
      titulo: "Visão cromática",
    },
    {
      pericia: "investigação",
      valor: 1,
      nivelMin: 2,
      titulo: "Visão cromática",
    },
    {
      ataque: true,
      valor: 2,
      nivelMin: 2,
      titulo: "Plumadagas boreais",
      condicional: "precisa estar com asas ativas",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 3,
      titulo: "Dominação Crepuscular Treinada",
      substitui: "Dominação Crepuscular Inicial",
    },
    {
      pericia: "persuasão",
      valor: 2,
      nivelMin: 4,
      titulo: "Asas da Aurora treinadas",
      condicional: "precisa estar com asas ativas",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 5,
      titulo: "Dominação Crepuscular Avançada",
      substitui: "Dominação Crepuscular Treinada",
    },
    {
      ataque: true,
      valor: 3,
      nivelMin: 5,
      titulo: "Vigor matinal",
      condicional:
        "precisa ter resistido a ataques no espectro psicológico (bônus dura uma rodada)",
    },
  ],
  éris: [
    {
      pericia: "furtividade",
      valor: 1,
      nivelMin: 1,
      titulo: "Amigo da onça",
    },
    {
      pericia: "enganação",
      valor: 2,
      nivelMin: 1,
      titulo: "Mentirosa profissional",
    },
    {
      ataque: true,
      valor: 2,
      nivelMin: 2,
      titulo: "Miss negativa",
      condicional:
        "quando alguém tiver falha crítica (vale para o seu próximo ataque apenas)",
    },
    {
      pericia: "enganação",
      valor: 2,
      nivelMin: 2,
      titulo: "Oratória caótica",
      condicional: "precisa ter a bifurcação",
    },
    {
      pericia: "performance",
      valor: 2,
      nivelMin: 2,
      titulo: "Oratória caótica",
      condicional: "precisa ter a bifurcação",
    },
    {
      pericia: "intuição",
      valor: 2,
      nivelMin: 3,
      titulo: "Percepção de anseios",
    },
  ],
  eros: [
    {
      pericia: "arqueirismo",
      valor: 2,
      nivelMin: 2,
      titulo: "Disparos do amor",
    },
    {
      pericia: "persuasão",
      valor: 2,
      nivelMin: 2,
      titulo: "Asas angelicais",
      condicional: "precisa ter a bifurcação",
    },
    {
      pericia: "persuasão",
      valor: 3,
      nivelMin: 4,
      titulo: "Asas angelicais - nível 4",
      substitui: "Asas angelicais",
      condicional: "precisa ter a bifurcação",
    },
    {
      ataque: true,
      valor: 1,
      nivelMin: 4,
      titulo: "Aura dos amantes",
      condicional: "+1 para cada aliado apaixonado (max 4)",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 5,
      titulo: "Se ame mais",
      condicional: "precisa ser um teste de inteligência",
    },
  ],
  fântaso: [
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 1,
      titulo: "Andarilho dos Sonhos",
      condicional: "precisa estar no Demos Oneiroi",
    },
    {
      pericia: "performance",
      valor: 2,
      nivelMin: 1,
      titulo: "Metamorfose inicial",
    },
    {
      pericia: "enganação",
      valor: 2,
      nivelMin: 2,
      titulo: "Comportamento imprevisível",
    },
  ],
  feme: [
    {
      pericia: "investigação",
      valor: 1,
      nivelMin: 1,
      titulo: "Escuta a fofoca",
    },
    {
      pericia: "percepção",
      valor: 1,
      nivelMin: 1,
      titulo: "Escuta a fofoca",
    },
    {
      pericia: "religião",
      valor: 2,
      nivelMin: 2,
      titulo: "Glorifica muito",
      condicional: "precisa ter a bifurcação",
    },
  ],
  hebe: [
    {
      pericia: "oficios",
      valor: 2,
      nivelMin: 3,
      titulo: "Master chef",
    },
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 5,
      titulo: "Padroeira das Noivas",
      condicional: "precisa estar acompanhada da pessoa amada, ambos recebem",
    },
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 6,
      titulo: "Razão e Sensibilidade",
      condicional: "precisa estar com alguém com quem já foi em batalha antes",
    },
  ],
  hécate: [
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 1,
      titulo: "Dominação Arcana Inicial",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 3,
      titulo: "Dominação Arcana Treinada",
      substitui: "Dominação Arcana Inicial",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 5,
      titulo: "Dominação Arcana Avançada",
      substitui: "Dominação Arcana Treinada",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 1,
      titulo: "Vantagem Submundana",
      condicional:
        "precisa estar em ambientes submundanos ou com alta concentração de espíritos, morte e cadáveres",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 2,
      titulo: "Congregação bruxa",
      condicional: "soma 1 para cada aliada bruxa (max 3)",
    },
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 3,
      titulo: "Levitação",
    },
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 4,
      titulo: "Filha da Lua",
      condicional:
        "precisa estar de noite (das 18h às 6h) e tem que ser um teste",
    },
    {
      pericia: "enganação",
      valor: 3,
      nivelMin: 5,
      titulo: "Imposição mediúnica",
      condicional: "para lidar com espíritos",
    },
    {
      pericia: "persuasão",
      valor: 3,
      nivelMin: 5,
      titulo: "Imposição mediúnica",
      condicional: "para lidar com espíritos",
    },
  ],
  hélio: [
    {
      pericia: "arcanismo",
      valor: 1,
      nivelMin: 1,
      titulo: "Dominação Solar Inicial",
    },
    {
      pericia: "arcanismo",
      valor: 2,
      nivelMin: 3,
      titulo: "Dominação Solar Treinada",
      substitui: "Dominação Solar Inicial",
    },
    {
      pericia: "arcanismo",
      valor: 3,
      nivelMin: 5,
      titulo: "Dominação Solar Avançada",
      substitui: "Dominação Solar Treinada",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 1,
      titulo: "Vantagem solar",
      condicional: "precisa estar de dia (das 6h às 18h)",
    },
    {
      pericia: "atletismo",
      valor: 1,
      nivelMin: 2,
      titulo: "Domínio do Sol",
    },
    {
      pericia: "condução",
      valor: 1,
      nivelMin: 2,
      titulo: "Domínio do Sol",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 2,
      titulo: "Sol da Meia-noite",
      condicional: "precisa ter a bifurcação",
    },
  ],
  héracles: [
    {
      pericia: "sobrevivência",
      valor: 2,
      nivelMin: 2,
      titulo: "Trabalha e trabalha",
    },
    {
      pericia: "combate desarmado",
      valor: 2,
      nivelMin: 2,
      titulo: "Cabeça com cabeça",
      condicional: "precisa ter a bifurcação",
    },
    {
      pericia: "todas",
      valor: 2,
      nivelMin: 3,
      titulo: "Doze trabalhos",
      condicional: "Precisa estar em missão",
    },
    {
      pericia: "todas",
      valor: 1,
      nivelMin: 5,
      titulo: "Viciado em missões",
      condicional: "+1 a cada rodada, até 3, mas precisa estar em missão",
    },
  ],
};
